### ISSUE TITLE
`ScopedPtr` could fail with C++11 support

### ISSUE THREAD

**Issue by dmcdougall** [libqueso/queso#397]
After a conversation with @roystgnr, it has occurred to us that falling back to `boost::scoped_ptr` from `std::unique_ptr` could produce code that doesn't compile.  The reason for this is that these two objects are fundamentally different.  `std::unique_ptr` permits the transfer of ownership, whereas `boost::scoped_ptr` does not.

**Comment by pbauman** [comment]
In theory, yes, the user could write cod that has some `std::move` if their compiler has `std::unique_ptr`. However, in my mind, we call it `ScopedPtr` to indicate that this is not intended for using move semantics (and I named it that since the fallback is `boost::scoped_ptr`). I have it use `std::unique_ptr` first since that's what we'd replace these with once we mandate C++11, it would be possible to not need Boost, and `std::unique_ptr` is essentially a superset of `boost::scoped_ptr`.

What are you suggesting we do instead?

**Comment by roystgnr** [comment]
This is a misleading issue title.  The risk here isn't that we'll write proper ScopedPtr code which will fail with unique_ptr under the hood; the risk is that we'll write *improper* ScopedPtr code, we won't notice because it will succeed with unique_ptr under the hood, and then it will fail as soon as someone builds with C++03 instead.

So it's not an *urgent* issue (everything's working now), it's just a likely source of real issues down the road.

**Comment by pbauman** [comment]
I get it, I just don't know what a better solution is.

**Comment by roystgnr** [comment]
Here's a silly thought: instead of defaulting to C++11 when available and falling back on boost next, why don't we default to boost?  Then the bulk of developers will be using a real scoped_ptr and so unlikely to write code that expects anything more permissive.

**Comment by pbauman** [comment]
I guess as long as we're mandating boost, that's fine. I'd ordered that way originally to permit us to move away from Boost.

**Comment by pbauman** [comment]
Just to defend myself a little, I had pointed all this out when I put in #368 originally.

**Comment by dmcdougall** [comment]
> This is a misleading issue title.

Sorry about that.

> I guess as long as we're mandating boost, that's fine. I'd ordered that way originally to permit us to move away from Boost.

Ok I understand, so from this I take it that what we should do is add a little more detail to the documentation (besides just the name) to add the caveat that you shouldn't assume you can transfer ownership, even though it is technically possible with C++11.
